FredHutch/wiki

- CONTRIBUTING.md
- README.md
- _config.yml
- _data/sidebars/domain_one_sidebar.yml
- _data/sidebars/domain_two_sidebar.yml
- _data/sidebars/home_sidebar.yml
- _data/topnav.yml
- pages/domain1/index.md
- pages/domain2/index.md
- pages/domain3/index.md
I edited some sidebars and pages to make them start to be similar to the three domains we're envisioning but mainly I just want to get my feet wet with what edits what and waht is connected to what.
@bmcgough I'm basically afraid to break anything you have done here, so I'm going to let you see if we can merge my first pass edits in as a pull request from a branch so that it should be easy to revert anything I did en masse and just ignore it.  It has nothing magical in it.
> a shot in the dark

- _data/sidebars/generation_sidebar.yml
- _data/sidebars/scicomp_docs_sidebar.yml
- _data/topnav.yml
- pages/bioinformatics/folderitems/inf_rbioconductor.md
- pages/generation/folderitems/clinicalCov.md
- pages/generation/folderitems/consentIRB.md
- pages/generation/folderitems/deidentification.md
- pages/generation/folderitems/dnaApproaches.md
- pages/generation/folderitems/hypothesis.md
- pages/generation/folderitems/labCov.md
- pages/generation/folderitems/naQComnibus.md
- pages/generation/folderitems/platformsData.md
- pages/generation/folderitems/privacySecurity.md
- pages/generation/folderitems/proposal.md
- pages/generation/folderitems/rnaApproaches.md
- pages/generation/folderitems/shareDeposits.md
- pages/generation/folderitems/specimenBanking.md
- pages/generation/folderitems/statistics.md
- pages/generation/gen_studydesign.md
I worked on the sidebar for the data generation page a bit and I'm going to merge this sucker in so that it can be a better demonstration for others.
> another pass of edits.

- WikiContent/bioinformatics/pipeworkflows/pipe_docker.md
We can leave this PR open until the Thursday meeting, so others can push to this branch if they want to add to or edit the Docker markdown
> Good start to the docker docs

- WikiContent/bioinformatics/pipeworkflows/pipe_docker.md
Let's get a few more comments and input from novices or SciComp about this before we merge it into the master again!
> Can I push to a merged branch?

- _computing/store_scratch.md
- _data/navigation.yml
pasted in section from sharepoint and added introduction
> first stab for scratch fs

- _computing/store_collaboration.md
Added docs on using S3 from Python. Added to `_computing/store_collaboration.md` rather than putting it in its own file.
> document using S3 from python

- _generation/gen_index.md
- _generation/human_shareDeposits.md
- Updated some headings on overview page to match table of contents.
- Edits for conciseness/readablity on the data sharing page.
> Edits to Data Sharing page

- _generation/labman_sharedequip.md
> Lab management shared

- _computing/store_databases.md
Let's get some more database info up into this page!!!  @plitwin I would love to include links and info about REDCap here.  I stole some text off your site and put a bunch of links in, but I want to make sure you have a chance to both be aware that this information exists elsewhere from your site, and be able to weigh in on how you want it presented.  FYI, the previous CYOA site is now morphing into something larger and I haven't had a chance to swing by mention it in person.  👍 
Paul, you should be able to edit the markdown file that has information about databases in it, so let me know if you can't!
> Databases!!

- _generation/human_consentIRB.md
- _generation/human_deidentification.md
- _generation/human_overview.md
- _generation/human_privacySecurity.md
- _generation/human_shareDeposits.md
- _generation/study_proposal.md
After a bunch of work in some google docs, this is the first pass of draft text that went through the IRO.
> IRO work is in!

- _computing/grants_publications.md
the long version will be stored in dirk's onedrive
> first draft on computational resources

- _computing/linux_linux101.md
> Added material to linux 101

- _bioinformatics/compute_uis.md
- _bioinformatics/prog_R.md
In the recent edits I noticed a bit of duplication that was emerging and the need to link between Notebooks and UIs and the R, RStudio page!!
> Quick r studio deduplication

- _computing/access_credentials.md
Minimal edits, no content change, just formatting
> Formatting repair on access_credentials.md

- _drafts/contentTemplate.md
- _includes/social-share.html
- _layouts/single.html
This addresses issue #160 to some degree.
> Make edit this page/comment link show up at top and bottom of pages

- _generation/human_privacySecurity.md
Changed language as no quick read chart.  Posting link to standard itself.
> Revised language line 30  added link

- _generation/human_privacySecurity.md
Addresses issues #168 and #60.
> Added data classification table

- _generation/datagen_Proteomics.md
this is far from done but I don't want it to get too far behind while I'm away on vacation. When I come back I'll have someone with domain knowledge review it because I'm pretty sure I don't know what I'm talking about.
> Proteomics

- _bioinformatics/dm_ingest.md
- _bioinformatics/dm_scratch.md
- _bioinformatics/dm_storage.md
- _computing/store_objectstore.md
- _computing/store_overview.md
- _computing/store_posix.md
I did a first pass on editing the best practices docs in Bioinformatics and tried to do more contextualizing and linking now that computing docs are up and linkable!!  This likely is a work in progress pull request, so weigh in!
> Data storage movement between Bioinformatics and Computing

- _compdemos/cluster_koshuBeta.md
When the beta session is complete, this information will move into a new page in the _computing section.
> Page for information about koshu cluster

- _bioinformatics/prog_overview.md
Addresses issue #188 as per @vortexing's suggestions.
> Update prog_overview.md to address issue #188 (how often is R updated on Rhino)

- _computing/store_collaboration.md
- _generation/human_privacySecurity.md
include services provided by O365 for email, storage, sharing. update examples of classified information, indicate identified data can not be on github, other minor changes
> update of language include Office 365 offerings

- _bioinformatics/dm_ingest.md
- _infdemos/github_pages-FHtheme.md
- _infdemos/ingest-Large-Data.md
Beginnings of a how-to for ingesting large data sets into FH supported storage without sending it through *Fast*.  ;)
> Ingesting large data demo for informaticians

- _computing/cluster_usingSlurm.md
Closes issue #200 
@atombaby  have any more elaboration inspiration here besides this very minimal link I put in???
> add link to slurm examples repo

- _compdemos/shiny.md
See issue #206 for complete history
> Punting additional instructions for getshiny site

- _compdemos/Docker.md
> some smaller fixes

- _compdemos/toolbox.md
toolbox is the API that HDC uses to get information about users.
> all info about toolbox.fhcrc.org

- _compdemos/tensorflow-gpu.md
> some more updates for Tensorflow

- _compdemos/toolbox.md
added example to toolbox doc: send an email notification to users who regularly write code at Fred Hutch to inform them of new features and we also want to CC their supervisors to increase awareness
> added coding example to toolbox

- _bioinformatics/compute_docker.md
- _compdemos/Singularity.md
moved and updated from old Wiki
> Singularity docs

- _compdemos/cluster_parallel.md
Hi-
I'm opening this pull request to get some help and advice on where I'm going with this page/topic.  It won't be ready to merge for a little while, but I really wanted to get some opinions from y'all on what I've got, where I think I'm going, and if the level of detail is appropriate.
I've started with a generic introduction on parallel computing- primarily highlighting the difference between threading and distributed and will then do non-language specific discussions on specific approaches to making work run in parallel.  I'm planning on additional pages attached to this one that then implement examples of those different approaches.
I'd like to get a little more content before merging this in, so if you want to contribute, feel free to edit on this branch.
Thanks
> New information on parallel computing

- _bioinformatics/prog_python.md
current examples in wiki throw error on rhino, added jupyterlab wrapper
> jupyter info update

- _bioinformatics/prog_R.md
> Update Bioinformatics R page to include GitHub installs

- _infdemos/usingS3withRhino.md
I forgot I had this little demo.  I put it in bioinformatics demo, but if y'all SciComp guys want to adopt it and make it yours, feel free!
> Working with S3 and Scratch

- _computing/store_collaboration.md
Anyone have anything to add about OneDrive?
> corrected OneDrive link

- _compdemos/Economy-local-large.md
- _compdemos/EconomyCommand-API.md
- _computing/store_objectstore.md
- _computing/store_overview.md
- _computing/store_posix.md
moved doc from old wiki 
how to migrate large data to Economy Local
and a few fixes
> a couple of storage fixes.

- _bioinformatics/prog_unixbash.md
Added couple of lines about perl. Mostly just giving some links to perl.org. @ptvan @vortexing. Related to issue #261.
> Rbarfield patch perl

- _data/navigation.yml
- _generation/gen_index.md
- _generation/multiple_testing.md
- _generation/study_hypothesis.md
- _generation/study_overview.md
> multiple testing

- _bioinformatics/compute_github.md
Addresses Issue #265  @dirkpetersen 
Add your edits to branch : "github-adjust"
> Adjust github page

- _generation/human_shareDeposits.md
add fairsharing.or list of sharing policies for various local and global agencies
> Update Human_Shareddeposits added resources

- _compdemos/nextflow.md
The updated config file has been tested with the most recent version of Nextflow against the Fred Hutch configuration of AWS Batch
> Update config file for Nextflow

- _compdemos/nextflow.md
Now that we have a good Nextflow module, update the docs accordingly
> Reference the working nextflow module

- _scicomputing/software_standards.md
> updated template docs in coding standards

- _scicomputing/compute_gpu.md
- _scicomputing/compute_jobs.md
- _scicomputing/compute_platforms.md
How to use the GPUs on koshu and gizmo.
> Add GPU docs

- .github/ISSUE_TEMPLATE/request-for-content.md
Correcting to two current domains, and specifying subsection.
> Updating issue template

- _compdemos/rslurm_example.md
Added a demo on using Rslurm for bioinformatics application.
> Created Rslurm example code

- _data/cluster_nodes.yaml
- _scicomputing/compute_gpu.md
- _scicomputing/compute_overview.md
- _scicomputing/compute_platforms.md
I moved @bmcgough 's table from the overview to the GPU-specific documentation and added a column to the overview table for the GPU data.
> Changes to GPU documentation

- _gendemos/DataManagementGuidance.md
> data management inspiration in a demo

- _scicomputing/compute_platforms.md
> fixing link

- _data/datastores.yaml
- _drafts/resource_overview.md
New tables will describe storage types and their capabilities and restrictions
> Testing new table for data storage

- _scicomputing/reference_training.md
Adding Tech Exchange as a community group, and target audiences for all groups.
> Community groups 

- _compdemos/nextflow.md
Definitely worthwhile to point users towards using `grabnode` to run workflows
> Small update to NF description

- _compdemos/microbiome_tools.md
- _compdemos/nextflow.md
I'd like to add a page describing some tools available for microbiome research. I'm not sure how to get this new page to show up in the right place -- I hope this is correct!
> Add documentation on microbiome analysis tools

- _data/navigation.yml
- _scicomputing/compute_gpu.md
- _scicomputing/compute_overview.md
- _scicomputing/compute_quickstart.md
Addresses #353 . Addition of this new page to sidebar headings will be included in #348.
> Adding quick start guide for large scale computing

- LICENSE.md
> added cc-by license

- _scicomputing/software_languages.md
> adding matlab to common languages

- _compdemos/microbiome_tools.md
More tools for microbiome analysis
> Added 16S, assembly, pan-genome

- _data/navigation.yml
- _scicomputing/access_overview.md
- _scicomputing/access_permissions.md
Let's get permissions highlighted in the wiki by adding this page.  
Closes Issue #384
> Permissions management

- _scicomputing/compute_quickstart.md
Hoping to provide a solution for issue #224 .
> Revamp of the computing quickstart

- _compdemos/nextflow.md
Also clean up the example code
> Point to `optimal` as the best queue to start with

- _scicomputing/reference_overview.md
- computingdemos.md
In an effort to address Issue #413 I thought perhaps these links might be better over in the overview page.
> Template repos move

- _compdemos/nextflow.md
> Update language on Nextflow version

- README.md
Draft Folders with Templates for New Content
NOTE: Any content that will need to be an entirely new page should be stored in the draft folder until it is ready for publication, and then an admin will move it to where it needs to go when it is considered finished.
For new content: https://github.com/FredHutch/wiki/blob/master/draft_drafts/contentTemplate.md
For new contributor entries: https://github.com/FredHutch/wiki/blob/master/draft_drafts/contributorTemplate.md
> Update README-fixed broken links

- _contributors/jburge.md
Creating a contributor md for jburge
> Creating a contributor md for jburge

- _compdemos/shiny.md
@dtenenba I just re-read the instructions as I was prepping to request deployment so I thought I'd tune up how it reads. 
I didn't change any substance, only formatting, a little order, and clarifying.
> refresh shiny!!!

- _scicomputing/software_linux101.md
and removed text that is now in the Quick start guide.  WOOT!
> add explainshell

- _compdemos/matlab.md
- _data/last_modified_dates.yaml
Recent conversations at office hours highlighted problems with the matlab docs.  I've updated these docs based on those interactions and problems we'd found following them.
> Update matlab docs

- _generation/human_privacySecurity.md
> updated broken link for security and storage solutions

- _compdemos/motuz.md
Added, tested, Swift instructions for Motuz.
> add Swift instructions for Motuz

- _generation/human_deidentification.md
Added a sentence to link to additional information posted.
> Inserted link to FH Guide HIPAA and Research

- _scicomputing/access_overview.md
- _scicomputing/store_overview.md
- outreach.md
cleaned up 
- outreach.md
- _scicomputing/access_overview.md
per #458 and #397
> Chilliwack patch 1

- _compdemos/nextflow.md
@sminot and I have added some "gotchas", FAQ, and more info to the nextflow docs. Hopefully we can set up a system where folks fork and PR changes to this doc when they have generally applicable nextflow solutions that others can benefit from here at the Hutch. That way people aren't running into the same issues as much or doing as much re-asking of questions in the nextflow channel on slack.
> Nextflow FAQ

- _compdemos/microbiome_tools.md
Short description and link to workflow for bacterial genome assembly
> Add section Bacterial Genome Annotation

- _compdemos/nextflow.md
link to https://www.nextflow.io/docs/latest/tracing.html#tasks
> nextflow -with-report

- outreach.md
@vortexing @k8hertweck I cleaned up /outreach ie [wiki writer/editor](https://sciwiki.fredhutch.org/outreach/) bc I'm going to start reaching out to specific people now and direct them to that page for more info about the program as well as use this copy on the revised page in my messaging. So on that note I've added sections like the "Do you have a desire to..","Possible areas of interest and content development.." and cleaned up some of the other sections and it would be great for you both to review and sign-off as I want to make sure it's cool to mention payment (line 27) in the manner I did as well as speak about and describe the program in the way I am. Oh also feel free to add more to the "Possible areas of interest and content development.." section as I think giving specific …
> cleaned up /outreach/ ie wiki writer/editor

- _compdemos/nextflow.md
A new section describes how to ramp up memory allocation based on the number of failed attempts.
> New Section on Iterative Memory Allocation

- _scicomputing/reference_training.md
Fixed typos and added links for online locations
> Small updates to training

- _scicomputing/store_overview.md
- _scicomputing/store_posix.md
https://github.com/FredHutch/wiki/issues/429
> added table to fast file and some other changes

- _contributors/jdm.md
added my name to the contributors folder
> jdm-1 add *.md file

- _compdemos/nextflow.md
This is a minor update to the Nextflow docs which I think might be helpful.
I've tested this extensively, and I think it is extremely helpful for very large workflows, while not adding any problems for small workflows.
> Update example config with aws.client.maxConnections

- _scicomputing/compute_environments.md
- _scicomputing/compute_jobs.md
- _scicomputing/compute_parallel.md
I thought it'd be nice to put in some hooks to eventually elaborate on about workflow managers where they touch the existing content.
> Adding more stubs for the two workflow managers

- _compdemos/cluster_koshuBeta.md
- _compdemos/matlab.md
- _compdemos/motuz.md
- _compdemos/synology.md
- _compdemos/toolbox.md
I did some format editing in the Resource library to make the snippets that show as a preview on the compdemos page make more sense/be more consistent.
> Vortexing formatting review

- _compdemos/Singularity.md
Our docs were outdated and based on Singularty version2
> Singularity update to v3

- _compdemos/gizmo-node-beta.md
- nomachine available
- expanded environment module changes
- added GPU docs
> More gizmo beta documentation updates

- _compdemos/microbiome_tools.md
I just wanted to add a reference to one more tool for microbial genome analysis.
> Add a description of the circlator nextflow workflow

- _data/navigation.yml
- Scientific Computing "Training and Finding Help": to match overview file
- Data Generation "Study Design and Funding": for new page from @jnooraga
> update lefthand sidebar

- contentproviders.md
Seems legit.  Might as well wrap this in.
> Chilliwack patch #400: contribution information

- _scicomputing/access_credentials.md
- _scicomputing/software_managecode.md
> GitHub teams and permissions

- _scicomputing/reference_overview.md
Will address #373 
- streamlining "Training and Finding Help" section
> Overviews in Scientific Computing Section

- _scicomputing/software_python.md
> Updating pictures links, small spelling fixes

- _generation/clsp_clinicalCov.md
wanted to add some verbiage about broader availability of clinical data as well as reorg for better logical flow
> expanding on description of available clinical data

- _data/navigation.yml
> removing beginners from sidebar

- _scicomputing/software_python.md
Taking a stab at refreshing this page.  @k8hertweck - wasn't completely sure what python stuff you wanted more linking out to but am happy to do more if you have any suggestions.
Closes #555
> Refresh/python ides#555

- _compdemos/Singularity.md
> Singularity updates

- _scicomputing/software_python.md
Fixed subheadings in bold, and some errant strikethrough
remaining issue from #555 , for @zyd14 : what is python magic? there is a reference to "Some Serious Magic beans", which sounds like something that should be google-able, but isn't actually a thing? I don't know enough about python magic to be able to talk about this! Feel free to hack on this branch
> Python IDE formatting

- _contributors/sgglick.md
- _generation/clsp_clinicalCov.md
- _generation/clsp_overview.md
- _scicomputing/reference_training.md
oh well look at this piece of lovely, fat, low hanging fruit
> removing data commonwealth language

- _compdemos/tensorflow-gpu.md
- _data/cluster_nodes.yaml
- _scicomputing/access_credentials.md
- _scicomputing/access_methods.md
- _scicomputing/compute_environments.md
- _scicomputing/compute_gpu.md
- _scicomputing/compute_grants.md
- _scicomputing/compute_jobs.md
- _scicomputing/compute_overview.md
- _scicomputing/compute_platforms.md
This PR captures changes necessitated by the upgrade and changes in the Bionic environment.  I've got some of the changes- mostly removing references to the largenode partition and updates to NX access.  I haven't updated module names in examples.
I am hoping to roll this out with the switch to the bionic environment as the default (16 June).
> Changes to reflect new Bionic flavor rhino/gizmo compute environment

- _scicomputing/access_methods.md
note about how screen interacts with rhino and method to more easily keep track of _screens_.
> small note about screen use on the rhino cluster

- _contributors/WhiteAu.md
- _contributors/esilgard.md
- _contributors/ritche_long.md
starting to think about adding on avatars for contributions
> I swear I'm not totally sandbagging...there's a method to the madness

- _compdemos/first_rhino.md
> Step-by-step process for logging on to rhino

- _scicomputing/store_overview.md
- Update Storage Allocation and Costs due to
new chargeback charges announced on 7/29/2020
> Update Storage Allocation and Costs table

- _compdemos/first_rhino.md
- _compdemos/howtoRhino.md
Trying to fix the formatting and clean things up a bit (let's have how to rhino not talk about gizmo!!!). Hopefully closes #574 .
> how to rhino quick tune up.

- _scicomputing/compute_jobs.md
- add information on max/default for campus-new partition
- add commands to DIY
- discussion on long jobs
> Wall Time Clarification (Issue 590)

- _scicomputing/store_posix.md
removed UNC path to dfs gateway
> remove unc path to dfs gateway

- _compdemos/nextflow.md
CWL is not a workflow manager, it's just a language that some tools make use of.
> remove CWL

- _compdemos/ssh_host_key_management.md
Adding additional language to help users new to the cluster AND to computing.
> SSH key clarifications

- _compdemos/first_rhino.md
- _scicomputing/compute_platforms.md
Revising based on feedback from MCB students.
> Clarifying grabnode questions

- _compdemos/Economy-storage.md
> some corrections and

- _scicomputing/store_overview.md
- added updates info about chargebacks
- changed features table of storage systems
> store_overview fixed

- _scicomputing/compute_jobs.md
- describe steps vs. jobs for sstat output
- add `-a` option to show batch & steps
> Update sstat usage

- _compdemos/Singularity.md
- organizational changes
- update to instructions for binding file systems in the container
> Update singularity docs

- _pythonModules/Python-3.7.4-foss-2019b-fh1.md
- _pythonModules/fhPython-3.8.2-foss-2020a-Python-3.8.2.md
- _rModules/fhR-4.0.3-foss-2020b.md
- _rModules/fhR-4.0.4-foss-2020b.md
- _rModules/fhR-4.0.5-foss-2020b.md
- _rModules/fhR-4.1.0-foss-2020b.md
- _rModules/fhR-4.1.1-foss-2020b.md
- _rModules/fhR-4.1.2-foss-2020b.md
- _scicomputing/compute_scientificSoftware.md
- pythonModules.md
@fizwit  I copied over the most recent stuff from the easybuild repo.  For now, manual seems fine but I thought since we remembered it today that we should strike while the iron is hot and get it done.
> Update Easybuild modules

- .gitignore
- _data/last_modified_dates.yaml
- _hdc/hdc_refgenomes.md
- _hdc/hdc_workflows.md
- _hdc/workflows/running/on_aws.md
- _hdc/workflows/running/on_gizmo.md
- _hdc/workflows/running/run_script.md
- _hdc/workflows/running_first_workflow.md
I felt like the nextflow docs needed to be updated to reflect the most current settings appropriate for gizmo/AWS, as well as the /shared/biodata/references/
> Nextflow updates

- _hdc/workflows/running/on_gizmo.md
This reflects some guidance that has been helpful for Nextflow users on gizmo
> Update guidance on configuring Nextflow for SLURM

- _scicomputing/compute_jobs.md
- _scicomputing/compute_overview.md
> Update schedmd link to reference current Slurm version

- _scicomputing/compute_overview.md
- _scicomputing/software_python.md
Jupyter notebook, lab, hub info was out of date.  Update compute_overview, Rstudio, and juypterhub have been turned off.
> update Python JupyterLab

- _scicomputing/compute_overview.md
- _scicomputing/software_python.md
Added a link to the other document that helps people think about where they need to run their code.
> Positioning of desktop computing

- _scicomputing/compute_overview.md
> Fix broken link

- _compdemos/Installing_AWSCLI_WSL
- _gendemos/Installing_AWSCLI_WSL
adding documentation on how to install and use AWS CLI on Windows Subsystem for Linux
> committing changes to aws-on-wsl branch

- .gitlab-ci.yml
I made a boo boo in the last PR, this will need to be merged in order to fix it.
> Check for orphan assets

- _scicomputing/access_credentials.md
> Fixed broken link

- .gitlab-ci.yml
Files an issue if there are orphan assets.
> File issue re orphans

- _scicompannounce/2022-09-10-rhino-gizmo-updates.md
Discuss- anything more we need to do?  Is this too much?
> Announcement for Maintenance Work

- _compdemos/globus-personal.md
I've been debugging a problem with globus and have picked up a few tips what might be useful...
> A few more details about setting up globus connect

- _scicomputing/store_objectstore.md
Fix some broken links and things that are no longer relevant on this single AWS page.
> make things more real/fix links

- .gitignore
- .gitlab-ci.yml
- Dockerfile
- Dockerfile.elasticsearch
- docker-compose-preview.yml
- docker-compose.yml
- elasticsearch/Dockerfile
- elasticsearch/Dockerfile2
- elasticsearch/indexer.py
- elasticsearch/indexer.sh
A bunch of infrastructural changes - no content changes. 
For details about this PR, please see this Slack post:
https://fhdata.slack.com/archives/CA2KRB666/p1664829419189939
> plumbing changes

- _data/navigation.yml
- _datascience/data_sharing.md
- _datascience/execute_sharing.md
- _datascience/hutch_courses.md
- _datascience/nih_data_sharing.md
This PR is primarily for the Data Science/DaSL section of the Wiki to start building some basic visibility into some of the early efforts we've undertaken that are Hutch oriented.  
Some of this content is borrowed from the course being made, and it links out to our blog post about drafts (so that we don't have to update the Wiki every 5 seconds).  
This could be a future home for final drafts as well so they are full-text searchable in the Wiki for additional find-ability.
> add NIH and course updates

- _scicomputing/store_objectstore.md
- a few more details about intelligent tiering
- reorganized some sections describing the managed service
- removed some references (explicit and implied) about economy local
> Intelligent tiering information

- _datascience/hutch_courses.md
Thought it'd be good to mention these two other courses/guides in this table too.
> add two more courses

- _scicomputing/store_objectstore.md
> Fix broken links & some spelling issues

- _data/cluster_nodes.yaml
minor correction to J node GPU type
> fix cluster_node GPU info

- _scicomputing/store_objectstore.md
Add additional information about charges and process
> Update FAQ question on additional S3 buckets

- _compdemos/Cromwell.md
> Update Cromwell guide info. 

- _scicomputing/store_objectstore.md
Closes #839 
Lists the three bucket regions we do support.
> updated AWS regions

- _scicompannounce/2023-04-19-gpu-limits.md
- _scicomputing/compute_job_scheduling.md
- _scicomputing/compute_jobs.md
> Add GPU limit information

- _compdemos/managing-module-versions.md
So a ticket came in the other day- raises a bunch of questions about how we handle module defaults.  Led me down a rabbit hole where I found this information.
I'm being a little opinionated- I'd like to be a little _more_ opinionated, but I'm not sure how to work that in.  Anyway, LMK whatcha think
> Add docs on lmod defaults

- _compdemos/onboard.md
As per a conversation we had today- this doc will identify resources that a new research community member could use to get started with computation at the Hutch.
This identifies starting points for getting help and information.
This will be sent as an email to our scientific relationship managers and research admins  so that they can, in turn, give this to new hires in their groups.
> Short TOC for resources that new people will find useful

- _scicomputing/software_linux101.md
> reference zsh

- _hdc/hdc_training.md
Removed broken links - addressing #767
> Update HDC Training resource page

- _compdemos/Apptainer.md
Discuss how to pull images specifically built for apptainer (not Docker images) and the one-time setup steps necessary to facilitate this.
> update apptainer docs

- _data/glossary.yml
- _scicomputing/software_R.md
After getting two requests for this in two days, it seemed like we needed some documentation for it.
One thing I'm not sure about is whether to tell people to use rhino, or should we have them use a gizmo node?
And if so, how does that work with nomachine? 
If I run grabnode inside a NoMachine terminal, I end up without X11 so the notebook does not run.
Does NoMachine run on gizmo nodes, or just on rhinos?
> Use jupyter with r

- elasticsearch/indexer.py
> remove nav content from html before converting to text and indexing

- _scicompannounce/2023-10-05-october-maintenance.md
Announcement for the october maintenance work
> Add announcement for maintenance

- _compdemos/mydb.md
Updating MYDB docs that use "fhcrc.org", changing to fredhutch.org.
Also changing the NGIX rewrite rules for mydb. All fhcrc.org will be rewritten to fredhutch.og
> domain change mydb.fhcrc too mydb.fredhutch

- _scicomputing/compute_job_scheduling.md
See issue #901 .  Updated links, fixed improperly formatted link
> Update links and references to limits

- _scicompannounce/2023-10-05-october-maintenance.md
Please add any details about change to the environment from the october maintenance work.  
- NVIDIA Driver version
- Kernel version
- Other package updates
- NX changes (if any)
> October Maintenance Release Notes

- _compdemos/aws-batch.md
> remove reference to nonexistent script

- _datascience/nih_data_sharing.md
No big changes but streamlined a bit and made things consistent across hutchdatascience.org and here.
> Consolidates/reorgs NIH Data sharing info. 

- _contributors/smoorthi.md
- _data/navigation.yml
Add smoorthi as a contributor.
> adding sita as a contributor

- _datascience/proof.md
**Updates**
- Removed DIY cromwell server documentation
- Delineated numbered sections and added a table of contents
- Added contributor contact info
- Fixed small grammatical typos
> Removing DIY cromwell text and adding numbered sections

- _hdc/hdc_index.md
Minor change, now that the cirro module is updated to 1.0.1.
> Update the Cirro CLI syntax

- _compdemos/globus-personal.md
- load the latest module version (i.e. don't specify version in the `ml` command)
- add instructions on restarting the endpoint
- misc changes for clarity
> Update module and instructions

- _scicompannounce/2024-04-02-new-hpc-temp-storage.md
- _scicomputing/store_overview.md
- _scicomputing/store_posix.md
- _scicomputing/store_scratch.md
- _scicomputing/store_temp.md
Minimal but likely sufficient section to start integrating the _temp_ storage platform into the wiki. Also snuck in patch for #959
> Intro to vast

- _scicomputing/store_databases.md
> fix redcap links

- _hdc/datagen_platformsData.md
Addressing Issue: https://github.com/FredHutch/wiki/issues/963
> Changing link to Hutchbase

- _data/navigation.yml
- _datascience/deidentification.md
- _datascience/phi.md
This page provides guidance on different types of data sets that may contain PHI or are derived from healthcare data.
It will update and replace this page: https://extranet.fredhutch.org/en/u/consortium-clinical-data-access/data.html#coded
Needs to be reviewed by Jenny before reviewed here. 
Also fixes #903
> Add PHI page

- _datascience/phi.md
Recent create of "PHI and research" page didn't include an actual definition of PHI.
> add PHI definition

- _dasldemos/code-review-guidance.md
Adding base for code review guidance page. Addressing issue #748
> Adding base for code review guidance page. Addressing issue #748

- _config.yml
- _data/navigation.yml
- _generation/gen_index.md
We think we have all links to these removed but it's possible not.  LEt's merge this in and then we can follow up to check on that.
> Removes data generation section

- _datascience/proof.md
Next set of PROOF release notes
> Proof release notes for May v1.0.0

- _compdemos/globus-personal.md
Reordered content, updated some content to be a little clearer (I hope).
> Update and clarify some steps in using connect personal

- _scicomputing/access_methods.md
- Adds step to e-mail the Service Desk if ssh command is not available. 
- Reorganize all additional steps under one heading
Resolves https://github.com/FredHutch/wiki/issues/1014
> add step for installing openssh-client + reorg

- _datascience/data_viz.md
Some minor edits, link updates, removal of old stuff, etc.
Could you please review and see if there are additional resources you would like to add if you were to point someone to this page during a DHC? 
What needs to be updated for the Python section?
> Dataviz edits

- _data/navigation.yml
- _datascience/data_wrangling.md
First draft of data wrangling page
> Data wrangling v0

- _scicomputing/access_methods.md
> Update VPN info

- _scicomputing/compute_cloud.md
Cloudshell is now available for all to use. There is no separate article for it though so I removed the hyperlink.
Closes #1002
> remove "coming soon" text

- _scicompannounce/2024-11-17-new-harmony-gpu-nodes.md
grabnode isn't supported on chorus at this time
> grabnode restrictions for chorus

- _compdemos/alphafold3.md
fix grammar, explain mapping of reference data
> update AlphaFold 3 compdemos

- _scicompannounce/2025-01-03-february-maintenance.md
> Small change to maintenance announcement

- _scicomputing/store_working.md
Update regarding quota notifications for /fh/working as these are not really optional as currently written.
> update quota notification docs for /fh/working

- _dasldemos/proof-troubleshooting.md
- Adding sectional bulletpoints to the top of the PROOF Troubleshooting article for easier navigation at the recommendation of @laderast (apologies for the delay, Ted!)
- Built the site locally, links work great.
> PROOF Troubleshooting Top Bulletpoints

- _datascience/privacy_security.md
[Written by @codebeaker] Implementing Ty et al.'s revisions to the data privacy and security page--changes to title, authors, content
The word doc version is here: https://fredhutch.sharepoint.com/:w:/r/sites/DaSL-DataGovernance/Shared%20Documents/Data%20Policy/Website/SciWiki%20Data%20Privacy%20and%20Security.docx?d=w2e9a2cb896924af78b72d9991eeb1230&csf=1&web=1&e=XQXco3
> [Sonu's] Hdc reframe srm

- _config.yml
- _datascience/using_workflows.md
The last remaining tweaks for Feb!
> Feb PR Hotfix

- _compdemos/python_virtual_environments.md
- _scicomputing/software_python.md
As the title indicates- updated documentation regarding Conda installers, how to use and how to configure.
> Update docs to reflect new conda usage

- _datascience/compliance_legal.md
Met with Ty today, implementing her updates 3/19
> updating compliance and legal

- _config.yml
- _scicomputing/compute_gpu.md
- assets/js/mermaid.js
Closes #1152 
Add mermaid graphs like this:
````markdown
```mermaid
sequenceDiagram
autoNumber
Alice->>John: Hello John, how are you?
John-->>Alice: Great!
Alice-)John: See you later!
```
> Add mermaid support

- _scicomputing/store_objectstore.md
- _scicomputing/store_overview.md
- _scicomputing/store_posix.md
- _scicomputing/store_scratch.md
- _scicomputing/store_task.md
- _scicomputing/store_temp.md
- _scicomputing/store_working.md
Remove recommendations for using scratch
Add deprecation notices for scratch
Add more documentation and links for working
Update secure data storage advice (NO PHI, contact OCDO)
Closes #960 
Closes #1165
> Updates for scratch, working, and secure

- _scicompannounce/2025-04-01-silver-latency.md
Some organization- add symptoms ahead of other information.  Add vscode configuration hints.  Add bit about disk space on silver affecting performance
> Reorg, add info about vscode

- _datademos/computational_rank.md
Update docs to use miniconda to get the conda installer
> Switch to miniconda

- _scicomputing/store_databases.md
- Noticed a couple of outdated/broken REDcap links, updated them accordingly.
- Fixes #1206 
- Built locally, links work great.
> Fixing broken REDcap links

- _compdemos/python_virtual_environments.md
Add that we don't have an anaconda license, refer to our mirror's documentation
> Add additional notice about Anaconda

- _compdemos/gizmo_partition_index.md
Update table to reflect current lmits
> Update limits in partition description

- _scicomputing/access_credentials.md
- direct questions to CLD via ITSD
- formatting, editing
> Update AWS instructions

- _datascience/proof.md
- _datascience/proof_regulated.md
- link from main proof page
- some formatting- i'd really like folks to grok that it's "stop existing, start anew"
> Some suggestions

- _datademos/cbio_how_to_prepare_files.md
- _datascience/cbioportal.md
Add panel information availability to sciwiki docs
> Cbio panel information

- _datascience/real_world_data.md
@monicagerber double checking with you that this is the correct link.
> fixed typo

- _data/glossary.yml
- _datademos/cbio_how_to_prepare_files.md
- _datademos/proof-how-to.md
- _datascience/data_wrangling.md
- _datascience/misc_training.md
- _datascience/proof.md
- _scicomputing/reference_training.md
- _scicomputing/store_databases.md
- _scicomputing/store_overview.md
Part one of many, part of #1265.
> Some dead link fixes
