FredHutch/wiki

_computing/cluster_cloudCompute.md, _computing/cluster_overview.md, _computing/cluster_rhinoGizmo.md, _computing/comp_index.md, _data/navigation.yml
I added a page for cloud computing and for rhino/gizmo, b/c these two pages are ones that many researchers have needed.  Maybe one will be fairly small for now (cloud), but the rhino page could get filled ASAP.
=> Proposed addition of pages for HPC on prem/cloud

.vscode/settings.json, _compdemos/vscode_markdown_howto.md
override user settings with work space settings for vs code
"pasteImage.path": "${projectRoot}/assets/${currentFileNameWithoutExt}/",
"pasteImage.basePath": "${projectRoot}/assets",
"pasteImage.forceUnixStyleSeparator": true,
"pasteImage.prefix": "/assets/"
this allows us to only temporarily change the settings while writing the wiki. it  also enforces the correct settings
=> change to workspace setting of vscode

_infdemos/github_pages-FHtheme.md
I added a brief demo about the FH-minimal-mistakes theme repo I made for Chao-Jen to hopefully fork/clone from to help with future documentation sites run through GitHub Pages where users would like to try to make it look Fred-Hutch-y.  
Once the other github page updates pull request gets merged, I'd like to add links to this demo in that text if possible.
=> add github pages theme repo demo page

_bioinformatics/compute_uis.md
Simplify the start instructions for jupyter notebooks on rhino's.
the option --no-browser will pick an unused port above 8888 automatically.
=> jupyter lab start instructions

_compdemos/ssh.md
Updating ~/.ssh/config example to make spacing consistent.
=> Consistent spacing in ~/.ssh/config example.

_data/cluster_nodes.yaml
Updated information in the cluster nodes table (`_data/cluster_nodes.yaml`) with J node information.  @bmcgough has this table published [here](https://sciwiki.fredhutch.org/scicomputing/compute_platforms/#gizmo)
I think this will close #138
=> Add outline for J node specs in nodes database

_scicomputing/comp_index.md
just quick change which would allow me to put sciwiki into my email footer and not any other info about scicomp support 
I'd like to put this 
https://sciwiki.fredhutch.org/scicomputing/
instead of this 
https://sciwiki.fredhutch.org/scicomputing/comp_index/
into my footer but currently it does not redirect and gets a 404
=> adding scicomp contact info

_scicomputing/store_overview.md
Uses a formatted, numbered list instead of inline numbering. Integrates language around ISO-approval instead of making an "and also" statement.
=> Storage overview: Update PHI requirements list

_scicomputing/reference_overview.md, _scicomputing/reference_training.md
- updated overview page to reflect categories contained
- moved content on training to new page, added info on community groups and office hours
Not sure if I got the links to other pages correct? Happy to make changes as necessary.
=> Scientific Computing reference section

_data/navigation.yml, _generation/gen_index.md, _scicomputing/comp_index.md
Addresses #348 by cross checking the sidebar subheadings across current page content. Includes Quick Start Guide from #368 so subheadings will still be complete when that's merged.
Additional changes: Includes a few minor updates to some subheadings to improve readability. Also removes the subheadings from the Data Generation and Scientific Computing overviews (so we don't need to update things in two places). Revised the summaries on the latter, given the subheadings are no longer present.
=> Updating navigation and descriptions on overviews

_scicomputing/compute_platforms.md
So this page: https://sciwiki.fredhutch.org/scicomputing/compute_platforms/
Needs help.  The autogenerated tables are great for maintaining updates in one place, BUT they do not allow for any explanatory text in between the tables.  Perhaps instead of looping through all the parts of the yml and making multiple tables at a time with no text in between, could we break that up a bit so we can explain what abbreviations and such are IN the table?  Also, why that table content is informative or interesting and how to use it?  
@bmcgough This is your baby so I am hesitant to fiddle with it at all.  Plus I don't actually know what some of the contents of the tables even are. ;)
=> compute platform refinements

_scicomputing/compute_jobs.md
- Issue #365 
-- In Examples section put new headers to describe each example. That way "Use largenode partition" shows up in the right hand pane of links. 
- Formatting changes: Examples header was H4 instead of H3
=> Fix formatting and largenode example

_scicomputing/compute_platforms.md
`howtoRhino.md` and `howtoGizmo.md` are both in `_compdemos/` but the Rhino link pointed to the `_scicomputing/` dir instead. I fixed the link, but it's possible that both files are in the wrong directory instead.
=> Fix link for howtoRhino page

_scicomputing/reference_training.md
deleted the info about the software development group as it's going away and renamed the python coding group to Python User Group
=> deleted Software Dev group stuff and renamed Py Group

_compdemos/nextflow.md
I made a mistake on the Nextflow FAQ PR and didn't include the full URL to https://tower.nf
This PR should fix that and enable the links that are currently live on the wiki.
=> Fix link to https://tower.nf

_scicomputing/software_R.md
Preferred way to use rstudio is via launch_rstudio_server script.
=> remove references to rstudio via X11 or rstudio.fhcrc.org

_scicomputing/compute_jobs.md
- Add more reasons to the "why job isn't running"
- Add more detail to the memory section on job submission
Explicitly call out that memory isn't a request-able/scheduled resources and how to deal with that in our environment
=> Add more information on memory and gizmo

_compdemos/ucsc-track-s3.md
There have been several requests by people who want to use the UCSC Genome Browser with their own data and it would be nice to be able to point people towards documentation that already exists, so here's an attempt at it.
Undoubtedly it needs some work but the bare minimum of information is there.
I'm also not sure where it should go and defer to @k8hertweck and @vortexing. @atombaby suggested compdemos so that's where I put it, but let me know if it should move.
In the meantime, I actually have someone who needs this and and I will just point them towards the page in this PR until it is merged.
=> document uploading files to s3 for use with UCSC Genome Browser

_compdemos/cluster_koshuBeta.md, _scicomputing/compute_jobs.md, _scicomputing/compute_parallel.md
We used SLURM_CPUS_ON_NODE to determine the number of cpus allocated to a job on the current node for years but we need actually use  SLURM_JOB_CPUS_PER_NODE per https://slurm.schedmd.com/sbatch.html
=> SLURM_JOB_CPUS_PER_NODE

_compdemos/maxquant.md, _data/last_modified_dates.yaml, _generation/datagen_proteomics.md
The MaxQuant proteomics software is now available on linux, so the cloud- and Windows-based pipeline we had before is now deprecated in favor of running MaxQuant on linux on the gizmo cluster, where it will not incur any costs.
This is documentation intended for users of that previous pipeline (or really anyone who wants to run MaxQuant).
=> Maxquant on linux docs

Gemfile, README.md
Dependency conflict between html-proofer and nokogiri resolved by updating html-proofer to highest version with common nokogiri version dependency.  Also fixed issue with Faraday incompatibility by pinning faraday based on [this](https://github.com/github/personal-website/issues/166). 
Updated README with some extra information on how to resolve various local build errors that I encountered when building on a clean system under WSL.
Would be helpful if someone else could try building this locally (ideally under Max and Linux) and verify that it works.
=> Fixed local wiki build.

_compdemos/first_rhino.md, _scicomputing/access_credentials.md, _scicomputing/compute_platforms.md
A common problem for new users is that a missing association to a PI account raises an error which isn't terribly clear about the reason or solution.  This adds additional information to key pages for new users.
=> Add snippets about invalid account errors for new users

_scicomputing/store_objectstore.md, _scicomputing/store_posix.md
Two additional pages (posix storage and object storage) had references to specific costs. I've removed specific thresholds for payment (e.g., 5 TB) and cost (specific $), but have retained notes that there are free allocations above which charges occur above a threshold.
I also corrected formatting for a few paths.
=> Removing additional references to data storage charges

_scicomputing/store_objectstore.md
I had someone ask about when the hybrid solution between economy local and fast will be available and sited this note. I have been told we are not going to be offering a hybrid model by Dirk so this should be removed.
=> Remove note about hybrid economy local

_compdemos/tensorflow-gpu.md
The three dots ` ... `at the end of the `singularity exec --nv docker://tensorflow/tensorflow:latest-gpu-py3 python3` command are making the command none functional for end users.
=> updating singularity command

_compdemos/galaxy-on-prem.md
Steps to use when toolbox doesn't have an association for a user or if you want galaxy installed someplace else.  Instructions for overriding "GALAXY_DIR"
=> Add steps to customize path to galaxy installation directory

_scicomputing/software_R.md
I need to deploy an updated
launch script (which behaves slightly differently) before I can roll out
the web application that enables launching RStudio Server from
a browser -- it depends on these changes.
I removed the bit about loading an R module before running the script,
this is no longer needed and will produce an error message.
This will all be moot soon - within a couple of days at most - when the web
app is rolled out.
=> This is very short term interim documentation.

_compdemos/Singularity.md
Ran into a corner case with TMPDIR and image builds.  Used this as an impetus to document both of those environment variables.
Not terribly happy with the discussion of tmpdir, but might suffice for now?
=> Update singularity instructions with notes on cache and tmp

.gitlab-ci.yml, Dockerfile, README.md, _compdemos/git_tips.md, _compdemos/gizmo-bionic-changelog.md, _compdemos/gizmo-bionic-known_issues.md, _compdemos/microbiome_tools.md, _compdemos/nextflow.md, _compdemos/rslurm_example.md, _compdemos/rslurm_intro.md, _compdemos/ucsc-track-s3.md, _generation/data-viz.md, _hdc/bioinformatics_library.md, _scicompannounce/2019-01-22-hpc-systems-upgrade-2019.md, _scicompannounce/2019-02-21-upgrade-env-modules.md, _scicomputing/access_overview.md, _scicomputing/compute_overview.md, _scicomputing/software_R.md, _scicomputing/software_examples.md, docker-compose-preview.yml, outreach.md, rancher-compose-yml
As [documented](https://github.com/FredHutch/wiki/blob/deploy-all-branches/README.md#automated-deployment) in the README in this PR,
Everything merged into the `main` branch
will be automatically deployed to 
[https://sciwiki.fredhutch.org](https://sciwiki.fredhutch.org).
Everything in any *other* branch pushed to GitHub will be deployed to 
[https://sciwiki-preview.fredhutch.org](https://sciwiki-preview.fredhutch.org),
which is only accessible inside the Fred Hutch network.
You can check what branch and what commit is reflected by going to 
[https://sciwiki-preview.fredhutch.org/info.txt](https://sciwiki-preview.fredhutch.org/info.txt).
This is actually already live (so check it out), because it does not need to be merged into main in order to take effect. When I pushed these commits it …
=> Deploy all branches

README.md, _compdemos/git_tips.md, _compdemos/gizmo-bionic-changelog.md, _compdemos/gizmo-bionic-known_issues.md, _compdemos/microbiome_tools.md, _compdemos/nextflow.md, _compdemos/rslurm_example.md, _compdemos/rslurm_intro.md, _compdemos/ucsc-track-s3.md, _generation/data-viz.md, _hdc/bioinformatics_library.md, _scicompannounce/2019-01-22-hpc-systems-upgrade-2019.md, _scicompannounce/2019-02-21-upgrade-env-modules.md, _scicomputing/access_overview.md, _scicomputing/compute_overview.md, _scicomputing/software_R.md, _scicomputing/software_examples.md, outreach.md
We are discussing having a CI/CD system to build non-main branches and deploy
them to some place where we can view them. For that and other reasons,
we want to remove absolute links so if we are looking at a branch hosted
somewhere, we don't want to accidentally click into the actual wiki
without realizing it.
Maybe in future we can add some functionality to CI/CD which checks for absolute links and either fixes it or throws an error during the build.
=> remove absolute links to the wiki

.bundle/config, .gitignore, README.md
So my workflow is easiest when I build this on a rhino/gizmo type system for testing.  Works well with the Ruby installed in app but a couple changes make this much easier:
- adding `.bundle/config` to install gems in _vendor
- adding the _vendor directory to gitignore
- adding some instructions
I'm only concerned that the bundle config will break the build- does anyone have any insights on that?
=> Add instructions and infrastructure for building on rhino

README.md
External IP of node not needed - use 0.0.0.0 instead. 
Other minor tweaks.
=> edits to 'build site on rhino' process

Dockerfile, Gemfile, README.md, build.sh, docker-build.sh
DON'T WANT TO MERGE straightaway, let's discuss first.
The goal of this PR is to eliminate the copious warnings that show up when building the site:
```
/home/dtenenba/dev/wiki/_vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
...repeats ad nauseam...
```
Deprecation warnings often turn into errors in later versions of software, so it's best not to ignore them.
To that end, this PR updates Ruby to 3.0.1 (not the latest version available, but the latest for which there is an Easybuild recipe ready to go, so the latest available on the rhinos/gizmos). 
Also, version pins are removed from Gemfile. I am not sure about the wisdom of leaving it like this. I removed them so that we would get the latest …
=> DON'T MERGE THIS YET - Update to ruby 3.0.1, eliminates warnings

_pathways/path-batch-computing.md
We briefly discussed this in our meeting today. 
The term "gizmo" kinda throws me off since I didn't know what "gizmo" was referring to but was looking for basic non-interactive job commands. Would probably be better for users if the word Gizmo was removed from the title. 
This is my first PR on this SciWIki. Please let me know what you would prefer as far as the PR process. Hope to contribute more PRs in the future if that would be helpful!
=> Delete "gizmo" from title 

_pathways/path-batch-computing.md
- missing "/" at the beginning of the target URL, made links relative
to this page
- see issue #787
=> Correct links in pathways

.dockerignore, .gitignore, .gitlab-ci.yml, Dockerfile, README.md, _config.yml, assets/js/customsearch.js, default.conf, docker-compose-preview.yml, docker-compose.yml, elasticsearch/Dockerfile, elasticsearch/indexer.py
This PR changes the way the site search works. Currently search queries go to an AWS Elasticsearch cluster in the old SciComp AWS account.
That account is going to be decommissioned soon. 
I looked at migrating this Elasticsearch cluster to the new SciComp AWS account and I ran into some problems. I may continue to investigate those problems, but along the way I had the idea that, now that we are hosting the wiki in our CI/CD platform (not GitHub pages), it would be possible to host our own single-node Elasticsearch cluster in a container that runs along with the wiki container. So that's what this is.
So in this PR, the indexing of the site is part of the site building process. It's not done anymore by an AWS Lambda function (that lambda function will need to be decommissioned, but the …
=> Use local elasticsearch

_datascience/hutch_courses.md
Added a table and multiple links for the Cluster 101 certification vs bookdown options to address confusion at Data House Calls.
=> better presentation of Fred hutch courses

Gemfile
Closes #828 in a different way.
I prefer not to have unpinned versions in the Gemfile so that the site is not broken by incoming (e,g. major version) changes.
I looked at the package at the top (bottom?) of the dependency tree that ultimately required an earlier version of faraday - jekyll-gist. It appears we do not actually use that package.
So I just took out the requirement of it in the Gemfile and the site appears to build and deploy just fine.
=> remove jekyll-gist dependency

.gitlab-ci.yml
This should (hopefully) fix some issues with the wiki occasionally failing to build.
=> ignore failure from docker rm

_compdemos/tensorflow-gpu.md, _scicomputing/compute_gpu.md
Use `--gpus` instead of the GRES interfaces.  Fixes #864
=> Update GPU options for slurm commands

_scicomputing/access_permissions.md
There was an incomplete discussion of file system permissions- this has been expanded slightly with the scope reduced to just fast-file.  The S3 access permissions information was obsolete and removed.
This includes information on collaboration directories and navigating blind parent directories
=> Clarify information about filesystem access permissions

_scicomputing/access_methods.md
otherwise users will just copy and paste the command (`ssh HutchID@rhino`), and it won't work.
=> be explicit that HutchID is a placeholder

_compdemos/Docker.md, _data/scicomp_resources.yaml
Users are still citing the wiki page about proxmox although it does not work.
This PR removes that content and also updates references to Rancher to refer to Docker Swarm.
=> remove references to proxmox

_scicomputing/software_R.md
Adds a link to the R-Ladies Seattle website. 
I used to host these at Fred Hutch and the TDS IRC sponsored us. Maybe more in the future.
=> Add R-Ladies to resources

_scicompannounce/2023-09-01-fasterq-dump-issue.md
Include use of `parallel-fastq` as a workaround.  Addresses #886
=> Update fasterq dump workaround instructions

_compdemos/store_job_local.md, _scicompannounce/2024-01-22-java-temporary-directory.md
Adds announcement for today (22 Jan 2024) and adds note to job local storage docs.
=> Add documentation for updates to Java temporary directory handling

_compdemos/ucsc-track-s3.md
Jekyll doesn't like it when text to be rendered appears on the same line as the initial 3 backticks of a fenced code block. 
GFM thinks it's the name of the language you are using.
=> syntax fixes

_scicomputing/software_python.md
* give a working example (note that this example is tied to a specific toolchain as we are having issues with 2023a); also the current default fhPython is not able to launch labs or notebooks
* removed documentation for notebooks as ppl should be using labs instead and having multiple similar sections is confusing. Added some text for notebook users explaining that labs are the same but better.
=> update jupyter lab documentation

_hdc/hdc_index.md
Fix a handful of links that point to the Cirro documentation site that were broken
=> Fix broken Cirro docs links

_scicomputing/access_credentials.md
- The first paragraph of the AWS CLI section of [this article](https://sciwiki.fredhutch.org/scicomputing/access_credentials/#configure-aws-cli) section points to additional reading, but the link just points back to the same section, which isn't super helpful.
- Pointing to AWS Access Key documentation instead and adding a "Resources" section to the bottom of the page.
- Fixes #995
=> Fixing link regarding AWS access keys and adding resources section

_datascience/proof.md
With the recent "v1.0" release of the overarching PROOF project, we are adding release notes to the PROOF product pages describing what has changed since it's original rollout. For more details, please visit the [PROOF umbrella repository](https://github.com/getwilds/proof/).
=> Adding release notes for v1.0 to the PROOF wiki page

.gitlab-ci.yml
Use a distinct, per-pipeline tag for the image that contains the search index.
This should prevent the index from being mismatched to the wiki content when deployed.
Closes #1025 (I hope)
=> attempt to fix #1025

_compdemos/aws-s3.md
The previous command had arguments reversed;
`aws s3 help cp` returns an error.
=> Fix order of arguments in S3 help command

_scicompannounce/2024-04-02-new-hpc-temp-storage.md, _scicomputing/store_posix.md, _scicomputing/store_temp.md
We have had two tickets from users for whom the original Mac Finder path that we had documented (`smb://hpc.chromium.fhcrc.org/temp.chromium`) did not work. Changing the path to `smb://fhcrc.org;USERNAME@hpc.chromium.fhcrc.org/temp.chromium` worked in both cases, so I figured we should document the path that works.
I am not sure why the original path stopped working and why the new one works (@atombaby can weigh in on that).
I'm also not sure if Windows users will run into the same issue, and if so, what the corresponding UNC path would be. If you know, can you add it to this PR?
=> update the Mac Finder path to /hpc/temp

_datascience/proof.md
- With the recent release of PROOF v1.1, we would like to add the latest release notes to the PROOF product page.
- Built the site locally and all looks good.
=> Adding PROOF v1.1 release notes to PROOF product page

_data/navigation.yml, _datascience/real_world_data.md
This PR:
- creates a new page on real-world data
- suggests a new sidebar organization 
The "PHI and Research" and "Data De-Identification" pages are moved under "Data Management and Sharing." 
I created "Biomedical Data" and "Data Science." I am hoping that in the future the Biomedical Data tab will include more information about public genomics data sets or other FH-specific resources. Data Science will be expanded to contain more resources on machine learning, statistics, and visualization. 
I would appreciate a review of the RWD page to make sure that the language is clear and I am not missing any critical Hutch resources.
=> Real-world data

_data/navigation.yml, _hdc/hdc_index.md
The top-level domain for Fred Hutch users to log in to Cirro is now https://fredhutch.cirro.bio
=> Update Cirro URL

_scicomputing/store_aspera.md, _scicomputing/store_aspera_shares.md, _scicomputing/store_collaboration.md
Resolves: https://github.com/FredHutch/wiki/issues/1028
I confirmed the links work by building locally on a rhino.
=> Add documentation on using the Aspera CLI

_compdemos/alphafold3.md
How to use AlphaFold 3 with GPU chorus nodes
=> AlphaFold 3 added to compdemos

_compdemos/alphafold3.md
This one is semi-urgent. The example script was missing a flag to `run_alphafold.py` that is needed, but was not exercised by our simple test case. This was discovered when a real user tried to run it with real data.
=> define --db_dir parameter to run_alphafold.py

_compdemos/aws-s3.md, _scicomputing/access_credentials.md
As noted in the changed files, R does not use SSO credentials directory, the way the AWS CLI and boto do.
So in order to use AWS in R, the user must run `aws sso login` first, which must be done by a human, and gives you a session that lasts 12 hours (or should, after the IDC timeout issue is resolved). 
This has implications for many use cases involving R and AWS, which we should discuss.
Hence this is a draft PR for now.
=> Document using AWS SSO credentials

_dasldemos/fh-cbio-intro.md, _datascience/cbioportal.md
- Currently, cBioPortal contact info points to [tfirman@fredhutch.org](mailto:tfirman@fredhutch.org), which massively increases the bus/lotto factor
- Switching to point to the [#cbioportal-support Slack channel](https://fhdata.slack.com/archives/C088E41ARV3) instead
- Also adding a blurb about IRB/datatype governance
- Fixes #1119 
- Built the site locally, looks good.
=> Switching FH cBioPortal contact to public Slack channel

_dasldemos/proof-how-to.md, _dasldemos/proof-troubleshooting.md
- Fixing text formatting issue in PROOF Troubleshooting article.
- Removing author lists from PROOF articles to match SciWiki contributing guidelines.
- All other material reflects the current state of PROOF in v1.1.
- Built pages locally, look good in terms of formatting.
=> Fixing typos and removing author lists from PROOF documentation

_datademos/fh-cbio-intro.md
- The Fred Hutch cBioPortal screenshots were pointing to the `dasldemos` directory, which I believe was recently changed to `datademos`, updating those paths.
- Checked for other instances of this switch, didn't find any, seems to be an isolated incident.
- Fixes #1148 
- Built locally, looks great.
=> Switching cBioPortal screenshot paths from dasldemos to datademos

_compdemos/Mountain-CyberDuck.md
Also remove Windows 7 instructions as they are outdated.
This page still references the old way of getting S3 credentials but that needs to be fixed in a separate PR.
=> document installing mountain duck from Self Service on mac

_config.yml
it works on the preview site
https://sciwiki-preview.fredhutch.org/
and we now have incremental search (for some reason)
=> try to get search working again

.gitlab-ci.yml, README.md
...or you will be able to, once this is merged (right now you can only see artifacts from the `add-artifacts` branch).
What's a build artifact? In this case it is a zip file containing the static, rendered site that was created by the GitLab CI/CD pipeline.
So before, to see how your changes look, you had to use the [preview site](https://sciwiki-preview.fredhutch.org/) which would show you the last non-`main` commit, but this could get overwritten by someone else's commit while you were looking at it. Or you had to build the site locally yourself, which is always a huge pain.
Now you can download a zip file that will show you how the site looks based on your latest commit to any branch. 
Read the changes to the README in this PR to see how it works (it's easy).
Closes #1176
=> you can now download build artifacts of any successful wiki build on any branch

_datascience/patient-data.md
- Noticed that the Fred Hutch Patient Data article points to the old URL on CenterNet.
- Fixes #1192 
- Built locally, link works as expected.
=> Fixing Patient Data Request Link

_datademos/proof-how-to.md, _datademos/proof-troubleshooting.md, _datascience/proof.md
- During recent DaSL courses, @caalo recently noticed that it's not obvious in PROOF documentation where it actually is, i.e. "proof.fredhutch.org" is no where to be found in the text, just a small hyperlink buried in a paragraph.
- Need to make the link more prevalent for new users to try it out, adding it as a subtitle at the top of the page, but open to other configurations as well.
- Fixes #1181 
- Built locally, works as expected.
=> Making PROOF URL more visible in documentation

.gitlab-ci.yml
In [9809576](https://github.com/FredHutch/easybuild-life-sciences/commit/98095764ebf40680e17a3a6cce13c1df2085fcbb) of the easybuild repo, a file used by the GitLab pipeline that builds the wiki was moved and renamed. This change should fix the build issue.
=> update file name and path

_compdemos/howtoRhino.md, _datademos/running_first_workflow.md, _scicomputing/compute_platforms.md
- @dtenenba mentioned that the link to the "First Rhino" page wasn't working, turns out we shifted that content elsewhere.
- Rerouting all references of "First Rhino" to interactive session Pathway, access methods, and grabnode articles.
- Fixes #1156 
- Built locally, links work as expected.
=> Pointing "first-rhino" hyperlinks to other resources

_compdemos/python_virtual_environments.md, _datademos/computational_rank.md
Update references from miniconda to miniforge.  Miniforge is the preferred and recommended conda provider- while miniconda has a less restrictive license than anaconda, it is still an Anaconda license whereas Miniforge is BSD-3
=> Update references to miniconda with miniforge (preferred conda provider)

README.md, _compdemos/Cromwell.md, _compdemos/git_tips.md
[Atom is no longer receiving security updates](https://github.blog/news-insights/product-news/sunsetting-atom/), so I do not think we should recommend that people use it. Also fixed typos on pages where there were references to Atom.
=> removed references to atom
